In [1]:
from utz import *
from nj_crashes.paths import ROOT_DIR
from njsp import crashes
from njsp.paths import PROJECTED_CSV
from njsp.ytc import to_ytc
from njsp.ytd import oldest_commit_rundate_since, projected_roy_deaths
from njsp import Ytd

chdir(ROOT_DIR)

In [2]:
ytd = Ytd()
prv_rundate = ytd.prv_rundate
prv_rundate

Searching for oldest commit with rundate ≥2025-04-19
Found rundate 2025-04-18 10:00:01 < 2025-04-19 at commit 65d6471e; returning commit 35f4942

'2025-04-19 10:00:02'

In [3]:
prv_ytd_ratio = ytd.cur_ytd_deaths / ytd.prv_ytd_deaths
pct_change = (prv_ytd_ratio - 1) * 100

print(f'As of {ytd.prv_rundate}, NJSP was reporting {ytd.prv_ytd_total} YTD deaths')
print(f'Current YTD Deaths ({ytd.rundate}): {ytd.cur_ytd_deaths}')
print(f'Previous year YTD Deaths (adjusted; {ytd.prv_rundate}): {ytd.prv_ytd_deaths}')
print(f'Projected {ytd.cur_year} total: {ytd.projected_year_total}')
print(f'{pct_change:.1f}% change')

As of 2025-04-19 10:00:02, NJSP was reporting 147 YTD deaths
Current YTD Deaths (2026-04-19 10:00:01-04:00): 144
Previous year YTD Deaths (adjusted; 2025-04-19 10:00:02): 146.99998430694674
Projected 2026 total: 577.3570505718835
-2.0% change

05c7ec178e5edae6e0b6a1acc1636e3c89025818: FAUQStats cache miss: 2025, Sat Apr 19 10:00:02 EDT 2025

Find the oldest commit with rundate less than 1 year ago, load crashes from that time:

In [4]:
prv_crashes = ytd.prv_ytd_crashes
prv_crashes

,CCODE,CNAME,MCODE,MNAME,HIGHWAY,LOCATION,FATALITIES,FATAL_D,FATAL_P,FATAL_T,FATAL_B,INJURIES,STREET,dt
ACCID,,,,,,,,,,,,,,
13682,12,Middlesex,1221,South Brunswick Tws,130,State Highway 130,1.0,0.0,1.0,0.0,0.0,NaN,NaN,2025-01-01 07:24:00-05:00
13739,21,Warren,2113,Knowlton Twsp,80,Interstate 80,1.0,0.0,1.0,0.0,0.0,NaN,NaN,2025-01-02 15:15:00-05:00
13686,11,Mercer,1103,Hamilton Twsp,95,New Jersey Turnpike MP 59.2,1.0,0.0,0.0,1.0,0.0,NaN,NaN,2025-01-02 22:01:00-05:00
13694,12,Middlesex,1209,Old Bridge Twsp,444,Garden State Parkway MP 122.2,1.0,1.0,0.0,0.0,0.0,0.0,NaN,2025-01-04 09:56:00-05:00
13691,04,Camden,0416,Haddon Twsp,130,State Highway 130,1.0,1.0,0.0,0.0,0.0,NaN,NaN,2025-01-07 06:38:00-05:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13855,08,Gloucester,0802,Deptford Twsp,55,State Highway 55 MP 58.4,1.0,1.0,0.0,0.0,0.0,NaN,NaN,2025-04-16 00:11:00-04:00
13857,17,Salem,1707,Oldmans Twsp,295,Interstate 295 MP 7.2,1.0,0.0,0.0,1.0,0.0,0.0,NaN,2025-04-16 19:00:00-04:00
13858,18,Somerset,1806,Bridgewater Twsp,NaN,Woodlawn Ave,1.0,1.0,0.0,0.0,0.0,NaN,Woodlawn Ave,2025-04-17 10:17:00-04:00
13860,06,Cumberland,0613,Upper Deerfield Tws,77,State Highway 77 MP 7.5,1.0,0.0,1.0,0.0,0.0,1.0,NaN,2025-04-17 16:18:00-04:00
13859,08,Gloucester,0811,Monroe Twsp,689,County 689 MP 5,1.0,1.0,0.0,0.0,0.0,NaN,NaN,2025-04-17 23:56:00-04:00

Load previous year YTD and final counts, and current year YTD counts:

In [5]:
prv_year = ytd.prv_year
cur_year = ytd.cur_year

prv_ytc = to_ytc(prv_crashes)
prv_ytd = prv_ytc.loc[prv_year]

prv_end = to_ytc(ytd.prv_end_crashes).loc[prv_year]

cur_ytc = to_ytc(ytd.cur_ytd_crashes)
cur_ytd = cur_ytc.loc[cur_year]

cur_ytd

            driver  passenger  pedestrian  cyclist  crashes
county
Atlantic         4          0           2        1        7
Bergen           4          0           2        0        6
Burlington       8          2           0        0        8
Camden           4          1           3        1        8
Cumberland       2          0           1        0        3
Essex            4          1           8        0       12
Gloucester       4          2           1        1        7
Hudson           1          0           5        0        6
Hunterdon        2          0           0        0        2
Mercer           3          1           4        0        7
Middlesex       11          1           5        0       17
Monmouth         4          1           4        0        9
Morris           5          0           5        0       10
Ocean           10          1           1        0       11
Passaic          1          2           0        0        2
Salem            4          0           0        0        4
Somerset         3          0           1        0        4
Sussex           1          0           1        0        2
Union            4          0           6        0       10
Warren           1          0           1        0        2

Compute fraction of current year that has elapsed (year-to-date; "YTD") and still remains (rest-of-year; "ROY"):

In [6]:
cur_ytd_frac = ytd.cur_year_frac
cur_roy_frac = 1 - cur_ytd_frac
print('%.1f%% through the year, %.1f%% remaining' % (ytd.cur_year_frac * 100, ytd.cur_roy_frac * 100))

29.7% through the year, 70.3% remaining

Combine previous year YTD / end with current year YTD:

In [7]:
def melt(df, name):
    return (
        df
        .melt(ignore_index=False, var_name='type')
        .set_index('type', append=True)
        .value
        .rename(name)
    )

z = sxs(
    melt(prv_ytd, 'prv_ytd'),
    melt(prv_end, 'prv_end'),
    melt(cur_ytd, 'cur_ytd'),
).fillna(0).astype(int)
z

                    prv_ytd  prv_end  cur_ytd
county     type
Atlantic   driver         6       18        4
Bergen     driver         5       22        4
Burlington driver         6       24        8
Camden     driver         9       20        4
Cape May   driver         2        9        0
...                     ...      ...      ...
Salem      crashes        4       18        4
Somerset   crashes        7       13        4
Sussex     crashes        1       11        2
Union      crashes        7       26       10
Warren     crashes        6       10        2

[105 rows x 3 columns]

In [8]:
def project_roy(r):
    return int(round(projected_roy_deaths(r.prv_ytd, r.prv_end, r.cur_ytd, cur_ytd_frac)))

roy = z.apply(project_roy, axis=1).rename('roy')
projected = (
    (z.cur_ytd + roy)
    .rename('projected')
    .reset_index(level=1)
    .pivot(columns='type', values='projected')
)
projected

type        crashes  cyclist  driver  passenger  pedestrian
county
Atlantic         30        2      15          3          11
Bergen           30        0      20          1          11
Burlington       33        1      28          5           5
Camden           31        3      13          4          13
Cape May          6        0       5          3           0
Cumberland       16        0       9          1           6
Essex            46        0      12          5          33
Gloucester       24        2      13          6           4
Hudson           33        1       7          1          18
Hunterdon         7        0       4          1           1
Mercer           26        1      11          6           9
Middlesex        83        1      46          6          36
Monmouth         44        1      16          4          11
Morris           37        1      15          1          11
Ocean            51        1      38          7          11
Passaic          15        0       9          5           5
Salem            18        0      18          4           1
Somerset          9        0       6          1           2
Sussex           15        0       7          0           4
Union            31        1      14          3          15
Warren            5        0       3          1           2

In [9]:
projected.to_csv(PROJECTED_CSV)